### ISSUE TITLE
Improve how messages are published to avoid potential scalability issues

### ISSUE THREAD

**Issue by Tlvenn** [faye/faye-redis-node#17]
Hi,

It seems that the way the Redis backend is currently implemented, some scalability issues are bound to happen pretty quickly as soon as the message payload is not so small and there is a decent number of clients.

Looking on google, I saw a comment on hacker news on the same subject:

"I tried using faye and it died very quickly under load with the redis backend. For every message that you send it queues it up into a redis list for each faye server in the cluster to read which doesn't scale very well in their very chatty redis queue system."

The issue is the redis backend currenly maintains a queue of messages for each client. So the message and its payload is duplicated N times (N = number of clients) which is very not efficient.

Ideally, each message should be stored a single time in redis.

**Comment by jcoglan** [comment]
The original reason for this design is that it makes it a single operation for a client connection to get all its pending messages from its queue, and it makes it avoids the problem of detecting which process a client is connected to (which might be none) and detecting when a message has been routed to all relevant clients and can therefore be deleted.

There are other potential ways to implement this but I'd like to hear your suggestions for a better design first.

**Comment by Tlvenn** [comment]
Hi James,

Without trying to out think this, is there any obvious reason why we cant leverage the pubsub to distribute   messages to all clients without relying on a queue system given there is no guaranteed delivery beside that all connected clients at the time of publish should get the messages ?

**Comment by jcoglan** [comment]
That would result in most messages to polling clients, or any client that is intermittently partitioned. Faye should guarantee that messages are delivered to all subscribed clients regardless of whether they are currently physically connected; a system that doesn't do this isn't much use on the web.

**Comment by jcoglan** [comment]
Have you run into a specific problem with this yourself? If so, have you tried running https://github.com/myspace/faye-redis-sharded-node instead?

**Comment by Tlvenn** [comment]
I didn't run into a problem myself but seeing the comment on HN and then looking at the code, it is scary to see the messages being duplicated per each client...

Fair enough regarding the need of queues but why is there a need to duplicate the messages ? Cant we have a single set with all messages with a unique ID and then each client maintains their own queue of message IDs instead of duplicating the messages ? The lookup would be a tiny more expensive but I believe the tradeoff is worth it.

**Comment by Tlvenn** [comment]
Also I dont know if there is currently a way to force Faye to only handle websocket but if so, it would be interesting to pass down the info to the storage engine for further optimization. In the case of Redis, the pubsub could therefore be used as a delivery system which would be more efficient than maintaining queues per client/channel manually.

**Comment by jcoglan** [comment]
You could store each message by an ID, but it would mean you'd need to implement code to remove a message once all relevant clients had consumed it. It also means that flushing a client's queue needs one `LRANGE` to get all the IDs, then a `GET` for each message key, whereas now it's a single `LRANGE`.

You would also need to remove messages when consumed by all clients. You could do this by storing the number of routed clients on publish, then calling `DECR` every time a client reads the message or disconnects. Then you could conditionally remove the message if its counter is zero, either immediately after your `DECR` call or as part of periodic GC. You might also need to make sure this done atomically, so you'd need to wrap a `SETNX`-style lock around the procedure.

On the publisher side, we could then replace the `RPUSH` per client with: one `INCR` to get a new message ID (would need to wrap to deal with fixed int size) (or we'd need to pick a random one and use `SETNX` to check if it's used, in a loop), one `SET` to store the message, one `SET` to store the number of routed clients, and one `RPUSH` per client to add the ID to its queue.

To this design means less data is stored, but more commands are used on the publisher and consumer sides. I have no idea based on theory if this will result in better performance, and it probably depends on message size and volume. You'd need to implement it and benchmark it.

**Comment by jcoglan** [comment]
You can't make Faye only support WebSocket. The Bayeux protocol demands that handshakes are done via normal HTTP (although the Faye server accepts handshakes via any transport). There will always be clients and hosts that can't use WebSockets for a variety of reasons.

Even if all hosts, clients and proxies supported WebSocket, you are still going to get network partitions, especially with web-based clients, especially on mobile devices. Demanding that a client be connected in order to receive messages will typically result in substantial data loss.

Therefore you can't simply map a WebSocket connection down to a Redis subscription; messages will still need to be queued for when the client is partitioned. It would also severely break the transport layer/engine abstraction boundaries in undesirable ways.

**Comment by Tlvenn** [comment]
Hi James,

Thanks for the feedback, what you proposed is pretty much what I had in mind.
I totally agree that in some cases it will more likely be better and in some others, not so much.

Given the relative simplicity of the storage engine and its pluggable nature, I guess when the time comes, I can experiment and plug my own.

Maybe the documentation of the redis storage should mention that its design is more likely to work well if the payload or the number of clients are not too big.

**Comment by jcoglan** [comment]
It's pluggable exactly so people don't need to appeal to me to get improvements into their stack :) But if you do implement something that improves things I'll happily merge it. In the meantime I'll close this issue, but refer to it if you have PRs in future.
