### ISSUE TITLE
why redis don't contains the key of '/clients/' + clientId + '/messages'

### ISSUE THREAD

**Issue by yamateh** [faye/faye-redis-node#20]

**Comment by jcoglan** [comment]
Could you fill in the description on this issue? I'm not sure what you're asking about just from this title.

Can you describe what you were doing when you filed this issue, what you expected to happen and what you observed instead?

**Comment by civicevolution** [comment]
Faye deletes the queued messages key after reading the messages. Here is the code where this happens in faye-redis.js,

```
emptyQueue: function(clientId) {
    if (!this._server.hasConnection(clientId)) return;

    var key   = this._ns + '/clients/' + clientId + '/messages',
        multi = this._redis.multi(),
        self  = this;

    multi.lrange(key, 0, -1, function(error, jsonMessages) {
      if (!jsonMessages) return;
      var messages = jsonMessages.map(function(json) { return JSON.parse(json) });
      self._server.deliver(clientId, messages);
    });
    multi.del(key);
    multi.exec();
  },
```

"multi" is a redis transaction. It reads the messages in the range and then deletes the key. So once the messages are read, the key is removed until a new message is queued. Faye is typically notified via redis Publish when new messages are added to the queue, so the key/queue will be emptied out ASAP and therefore you won't see the key in redis.

**Comment by jcoglan** [comment]
Thanks for the explanation @civicevolution. @yamateh I'm going to close this issue because I believe the above comment answers your question. If you had further questions, then please do re-open with more details.
