### ISSUE TITLE
Recent update to redis (2.6.1) causes messages not to be broadcast

### ISSUE THREAD

**Issue by dynajoe** [faye/faye-redis-node#23]
I'm not exactly sure how to describe this except that publishing messages no longer works. I see subscriptions showing up in Redis. But no messages seem to be make it out. `publish` succeeds and there are no apparent errors.

From `npm list --long --parseable | sort`

NOT WORKING:

```
/app/node_modules/faye-redis/node_modules/redis:redis@2.6.1:undefined
/app/node_modules/faye-redis:faye-redis@0.2.0:undefined
/app/node_modules/redis-parser:redis-parser@2.0.0:undefined
```

WORKING:

```
/app/node_modules/faye-redis/node_modules/redis:redis@2.6.0-2:undefined
/app/node_modules/faye-redis:faye-redis@0.2.0:undefined
/app/node_modules/redis-parser:redis-parser@1.3.0:undefined
```

**Comment by mspensieri** [comment]
A thumbs up on the description isn't enough, +1 to this - we are facing the same issue

**Comment by jcoglan** [comment]
Can one of you please find out why this is not working? I would expect that something like this breaking in a patch release of a dependency be considered a bug in the dependency. Has anyone investigated?

**Comment by civicevolution** [comment]
Having the same problem, it is in faye-redis.js, specifically in

```
emptyQueue: function(clientId) {
    if (!this._server.hasConnection(clientId)) return;

    var key   = this._ns + '/clients/' + clientId + '/messages',
        multi = this._redis.multi(),
        self  = this;

    multi.lrange(key, 0, -1, function(error, jsonMessages) {
      if (!jsonMessages) return;
      var messages = jsonMessages.map(function(json) { return JSON.parse(json) });
      self._server.deliver(clientId, messages);
    });
    multi.del(key);
    multi.exec();
  },
```

the transaction doesn't execute in the same way anymore.

multi.exec() doesn't execute the callback in the lrange command, even though there is data available, but it does execute the "multi.del(key)" command and remove the queued messages.

In a working version, you can look at multi.queue and see this

```
  multi.queue
  [ [ 'MULTI' ],
    [ 'lrange', '/clients/123D/messages', 0, -1, [Function] ] ]

```

In the non-working version you'll see this instead:

```
multi.queue
  { [String: '[object Object]'] _capacity: 16, _length: 1, _front: 0 }

```

I haven't figured out how to fix it all out yet, but it seems that the callback in the transaction lrange() is simply ignored now.

In the working version, the lrange() callback is executed and the output from lrange() is captured and sent to the exec() callback

```
  >  multi = this._redis.multi()
  >  multi.lrange(key, 0, -1, function(error, msgs) { console.log("msgs:\n" + JSON.stringify(msgs, null, 2))})
  >  multi.exec(function (err, replies) {
  ...       console.log(replies);
  ...   });
  true
  > msgs:
  [
    "message A for 123",
    "message B for 123",
    "message C for 123"
  ]
  [ [ 'message A for 123', 'message B for 123', 'message C for 123' ] ]

```

Now in the broken version, the lrange() callback is ignored but the output from lrange() is still captured and sent to the exec() callback

```
  >  multi = this._redis.multi()
  >  multi.lrange(key, 0, -1, function(error, msgs) { console.log("msgs:\n" + JSON.stringify(msgs, null, 2))})
  >   multi.exec(function (err, replies) {
  ...       console.log(replies);
  ...   });
  true
  > [ [ 'message A for 123', 'message B for 123', 'message C for 123' ] ]

```

**Comment by civicevolution** [comment]
This [pull request](https://github.com/faye/faye-redis-node/pull/24) from lemieux points to the quickest solution.

The loose version of Redis in package.json caused an upgrade to a broken/incompatible version of Redis. Redis 2.6.0-2 seems to be the last known working version.

I took a quick look at redis/lib/multi.js and there are pretty extensive changes about how transaction commands and callbacks are handled.  Too many for me to dig into. It would seem they broke it.

I used npm shrinkwrap to save my hand edits to the package.json which seems to work without forking the faye-redis-node code.

You should see this in npm list

```

└─┬ faye-redis@0.2.0
  └─┬ redis@2.6.0-2
    ├── double-ended-queue@2.1.0-0
    ├── redis-commands@1.2.0
    └── redis-parser@1.3.0

```

**Comment by civicevolution** [comment]
I've reported this as a bug to node_redis 

[2.6.1 Ignores callback functions in transaction commands](https://github.com/NodeRedis/node_redis/issues/1089)

**Comment by jcoglan** [comment]
I would advise people to use `npm shrinkwrap` to pin their versions. The transaction commands breaking in a patch release smells like a bug in `redis` to me and I my general preference is to keep open-ended dependencies in my modules so that people can upgrade their transitive deps without requiring me to publish `faye-redis` every time `redis` is published.

**Comment by BridgeAR** [comment]
This is fixed in node_redis [v.2.6.2](https://github.com/NodeRedis/node_redis/releases/tag/v.2.6.2).

**Comment by jcoglan** [comment]
As I suspected, this is a bug that's now been patched in `redis`, so I'm going to close this issue.
